name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "akobashikawa@gmail.com"
        git config --global user.name "Antonio Kobashikawa"

    - name: Build and Deploy
      run: |
        npm ci
        npm run build
        npm run deploy
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
