name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: akobashikawa/vuepress-akc-bitacora
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: npm i && npm run build
        BUILD_DIR: src/.vuepress/dist/
